Add all features
swrggv/java-filmorate pull request #18
Opened 2022-07-26 13:49 UTC by a-grebnev-91-tech

2022-07-27 07:24 UTC, kukolev requested changes

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DirectorController.java
> +        log.info("Получен запрос к эндпоинту /directors. Метод POST");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменной director.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    ReviewService reviewService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Review review1 = reviewStorage.getReviewById(review.getReviewId());
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sql = "update film set film_name = ?, description = ?, release_date = ?, duration_film = ?," +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +        String sql = "SELECT * FROM film f " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        String sql = "update reviews set content = ?, is_positive = ? " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +        String sql = "delete from reviews where review_id = ?";
Здесь и в остальных запросах в классе нужно привести стиль оформления кода в запросах в соответствие с общим стилем. Так код будет единообразным.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        String sql = "update users set email = ?, login = ?, user_name = ?, birth_date = ?" +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/validators/DirectorValidate.java
> +        log.info("Проверка Id директора: " + directorId);
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)` или `log.warn(String.format("Some warning text for %s", val))` . Так код смотрится проще и тратится меньше ресурсов.

Аналогично нужно поправить в остальных местах кода, где есть логирование.

2022-07-27 07:24 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/validators/DirectorValidate.java
> +    public void validateNameAndExist(Director director) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-07-28 21:44 UTC, kukolev requested changes

2022-07-28 21:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +public class DirectorService {
Сейчас сервис является просто оберткой над хранилищем. Это может быть признаком проблемы, т.к. просто бессмысленные обертки это плохая практика - они не нужны. По моему тут не хватает функционала: нет валидации параметров, нет выброса исключений, если какие-то данные не найдены. 

Нужно наполнить этот сервис функционалом.

2022-07-28 21:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +@Slf4j
Эта аннотация здесь не нужна, т.к. нет логирования. Либо нужно добавить логирование в код.

2022-07-28 21:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/EventDbStorage.java
> +            throw new ModelNotFoundException("Event not found");
По моему выброс исключений логичней перенести на уровень выше, в сервис. Аналогично нужно поправить в других хранилищах.

2022-07-28 21:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/validators/DirectorValidate.java
> +public class DirectorValidate {
Название классов должно быть существительным или несколькими существительными. Здесь подойдет больше название `DirectorValidator`

2022-07-29 10:20 UTC, a-grebnev-91-tech commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/EventDbStorage.java
> +            throw new ModelNotFoundException("Event not found");
Не понял, почему кидать эксепшн в хранилке это плохо. Ведь там есть методы которые сами кидают, например SQLException.
Ведь когда у нас метод получения по айди не возвращает ни одной записи у нас по сути только три пути:
1. возвращать опшнл
2. возвращать нулл
3. кидать эксепшен
И у всех трех способов есть как плюсы, так и недостатки, на мой взгляд.

2022-07-29 17:18 UTC, kukolev approved these changes

2022-07-29 17:20 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/EventDbStorage.java
> +            throw new ModelNotFoundException("Event not found");
SQLException это все таки ошибки в SQL, но не в бизнес-логике. Отсутствие данных при селекте это ошибка в логике - с точки зрения хранилища ничего страшного нет, просто нет данных. Но именно сервис должен воспринять это как ошибку и кинуть эксепшен. Как-то так. Если что, давайте обсудим эту философию в слаке )

2022-11-07 10:24 UTC, merged